### ISSUE TITLE
Badge Icons (to-do)

### ISSUE THREAD

**Issue by jonpmarino** [jsiochi/GeoBadges#31]
- [ ] OSM Validator (5 star)
- [ ] OSM Surveyor (1 star, 2 star, 3 star, 4 star, 5 star)
- [ ] OSM Mentor (5 star)
- [ ] MapStoryteller (1 star, 2 star, 3 star, 4 star, 5 star)
- [ ] GeoPlunge Coach
- [ ] GeoPlunge Champion
- [ ] GeoMakers Balloon Mapper (3 star)
- [ ] GeoPackage Master (5 star)
- [ ] WebMap Context Master (5 star)
- [ ] OGC Developer (5 star)
- [ ] OGC TC (1 star, 2 star, 3 star, 4 star, 5 star)
